### ISSUE TITLE
vagrantで起動するとmakeが入っていないのでエラーになる。

### ISSUE THREAD

**Issue by propos-jp** [tokyo-metropolitan-gov/covid19#2610]
## 起こっている問題 / The Problem
Vagrantで使っているubuntu/bionic64 Boxにはビルドツールが入っていないので
ビルドエラーが発生する。

## ログ / log
  default: gyp ERR! stack Error: not found: make
    default: gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
    default: gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
    default: gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
    default: gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
    default: gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
    default: gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
    default: gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:171:21)
    default: gyp ERR! System Linux 4.15.0-91-generic
    default: gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--release"
    default: gyp ERR! cwd /home/vagrant/covid19/node_modules/fibers
    default: gyp ERR! node -v v13.12.0
    default: gyp ERR! node-gyp -v v5.1.0
    default: gyp ERR! not ok
    default: node-gyp exited with code: 1
    default: Please make sure you are using a supported platform and node version. If you
    default: would like to compile fibers on this machine please make sure you have setup your
    default: build environment--
    default: Windows + OS X instructions here: https://github.com/nodejs/node-gyp
    default: Ubuntu users please run: `sudo apt-get install g++ build-essential`
    default: RHEL users please run: `yum install gcc-c++` and `yum groupinstall 'Development Tools'`
    default: Alpine users please run: `sudo apk add python make g++`

## 期待する見せ方・挙動 / Expected Behavior
- 上記のようにmakeが入っていないのでエラーになる。
- vagrant_provision.shにsudo apt-get install g++ build-essentialを追加する。

## 起こっている問題の再現手段 / Steps to Reproduce
1. projectをcloneする。
2. vagrant upで起動。
3. 上記のエラーが出る。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux

**Comment by propos-jp** [comment]
簡単な修正なので対応します。
