### ISSUE TITLE
[ruby] やさしい日本語ページをリロードするとローディングで止まる

### ISSUE THREAD

**Issue by shgtkshruch** [tokyo-metropolitan-gov/covid19#3141]
## 起こっている問題 / The Problem
- https://ja-hira-covid19-tokyo.netlify.com/ja-basic を直接開くとローディングで止まります
- おそらくこちら https://github.com/tokyo-metropolitan-gov/covid19/issues/2764#issuecomment-610382548 と同様の現象だとおもいます

## スクリーンショット / Screenshot
Chrome の console の表示

```
Unchecked runtime.lastError: The message port closed before a response was received.
DevTools failed to parse SourceMap: file:///Users/shgtshruch/Library/Application%20Support/Google/Chrome/Defaul…xtensions/aeblfdkhhhdcdjpifhhbdiojplfjncoa/1.18.0_0/inline/injected.js.map
bec7b6f….js:2 [vue-analytics] Missing the "id" parameter. Add at least one tracking domain ID
cb02650….js:2 TypeError: Cannot read property '_transitionClasses' of undefined
    at Array.kr (cb02650….js:2)
    at T (cb02650….js:2)
    at cb02650….js:2
    at T (cb02650….js:2)
    at cb02650….js:2
    at T (cb02650….js:2)
    at cb02650….js:2
    at T (cb02650….js:2)
    at cb02650….js:2
    at T (cb02650….js:2)
DOMException: Failed to execute 'appendChild' on 'Node': This node type does not support this method.
    at Object.appendChild (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:41280)
    at m (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:54203)
    at v (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:53940)
    at _ (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:54289)
    at P (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:57675)
    at P (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:57610)
    at f.__patch__ (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:58087)
    at f.t._update (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:35026)
    at f.r (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:65490)
    at bn.get (https://ja-hira-covid19-tokyo.netlify.com/_nuxt/cb02650….js:2:27202)
```

## 期待する見せ方・挙動 / Expected Behavior
- やさしい日本語ページを直接表示してもローディングで止まらないこと

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://ja-hira-covid19-tokyo.netlify.com/ja-basic を直接開く
1. 他言語からやさしい日本語に切り替えてリロードする

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by shgtkshruch** [comment]
こちら私のほうで対応します。
