### ISSUE TITLE
ogp_builderでエラーが発生している

### ISSUE THREAD

**Issue by kikd** [tokyo-metropolitan-gov/covid19#4159]
## 起こっている問題 / The Problem
- ogp_builderでエラーが発生しており、OGPイメージが5/7日分から更新されていません。
  また、それ以降に作成された陽性率の推移のグラフについては、OGPのイメージが表示されていません。

## スクリーンショット / Screenshot

- Twitter Card Validatorで検証した結果
検査実施人数
![image](https://user-images.githubusercontent.com/5682821/81889952-bbd89380-95df-11ea-94fc-692ba9bf71ac.png)
陽性率の推移
![image](https://user-images.githubusercontent.com/5682821/81891160-baf53100-95e2-11ea-8115-593814a67c53.png)

- ogp_builderのログ

```
2020-05-08T06:09:27.1866056Z ##[group]Run ad-m/github-push-action@master
2020-05-08T06:09:27.1866609Z with:
2020-05-08T06:09:27.1867951Z   github_token: ***
2020-05-08T06:09:27.1868455Z   branch: master
2020-05-08T06:09:27.1868897Z   directory: .
2020-05-08T06:09:27.1869364Z ##[endgroup]
2020-05-08T06:09:27.2212327Z Started: bash /home/runner/work/_actions/ad-m/github-push-action/master/start.sh
2020-05-08T06:09:27.2258998Z Push to branch master
2020-05-08T06:09:27.8269805Z error: dst refspec refs/heads/master matches more than one
2020-05-08T06:09:27.8270862Z fatal: the remote end hung up unexpectedly
2020-05-08T06:09:27.8319224Z error: failed to push some refs to '***github.com/tokyo-metropolitan-gov/covid19.git'
2020-05-08T06:09:27.8323981Z Error: Invalid status code: 1
2020-05-08T06:09:27.8325071Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
2020-05-08T06:09:27.8325698Z     at ChildProcess.emit (events.js:210:5)
2020-05-08T06:09:27.8326757Z     at maybeClose (internal/child_process.js:1021:16)
2020-05-08T06:09:27.8327596Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5) {
2020-05-08T06:09:27.8328157Z   code: 1
2020-05-08T06:09:27.8328620Z }
2020-05-08T06:09:27.8329112Z Error: Invalid status code: 1
2020-05-08T06:09:27.8329944Z     at ChildProcess.<anonymous> (/home/runner/work/_actions/ad-m/github-push-action/master/start.js:9:19)
2020-05-08T06:09:27.8330542Z     at ChildProcess.emit (events.js:210:5)
2020-05-08T06:09:27.8331042Z     at maybeClose (internal/child_process.js:1021:16)
2020-05-08T06:09:27.8331759Z     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
2020-05-08T06:09:27.8416407Z Post job cleanup.
2020-05-08T06:09:27.9427278Z [command]/usr/bin/git version
2020-05-08T06:09:27.9492508Z git version 2.26.0
2020-05-08T06:09:27.9527284Z [command]/usr/bin/git config --local --name-only --get-regexp core\.sshCommand
2020-05-08T06:09:27.9575185Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'core\.sshCommand' && git config --local --unset-all 'core.sshCommand' || :
2020-05-08T06:09:27.9842499Z [command]/usr/bin/git config --local --name-only --get-regexp http\.https\:\/\/github\.com\/\.extraheader
2020-05-08T06:09:27.9884969Z http.https://github.com/.extraheader
2020-05-08T06:09:27.9886083Z [command]/usr/bin/git config --local --unset-all http.https://github.com/.extraheader
2020-05-08T06:09:27.9921481Z [command]/usr/bin/git submodule foreach --recursive git config --local --name-only --get-regexp 'http\.https\:\/\/github\.com\/\.extraheader' && git config --local --unset-all 'http.https://github.com/.extraheader' || :
2020-05-08T06:09:28.0227976Z Cleaning up orphan processes
```
 
## 期待する見せ方・挙動 / Expected Behavior
- OGPのイメージが更新されていること
- 陽性率の推移のグラフのOGPイメージが表示されること

## 起こっている問題の再現手段 / Steps to Reproduce
-  各コンポーネントをSNSでシェアする
または、
- [Card Validator](https://cards-dev.twitter.com/validator)で各コンポーネントのURLのプレビューを見る

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kaizumaki** [comment]
ご指摘ありがとうございます。以前からこちらの現象が起こることは認識しています。
```
error: dst refspec refs/heads/master matches more than one
```
とあることから調査しまして、 `refs/heads/master` というtagが存在してしまっているのが原因のようです。
そしてこのtagは、transifex-integrationが生成している可能性が高いことがわかりました。
Transifexのほうは変えようがないので、`.github/workflows/ogp_builder.yml` を修正して対処したいのですが、何かいいアイディアはありますでしょうか？

**Comment by kaizumaki** [comment]
とりあえずの対応として、 `refs/heads/master` のtagを削除することとします。

**Comment by kikd** [comment]
確認＋対応いただいてありがとうございます。
>Transifexのほうは変えようがないので、.github/workflows/ogp_builder.yml を修正して対処したいのですが、何かいいアイディアはありますでしょうか？

考えてみましたが、いいアイディアが思いつきませんでした…
workflowで毎回対象のタグを消すわけにもいかないでしょうし…

今のところ現象は発生していないのでこのissueはクローズし、いい案が出てきたら別途issue作成したいと思います。

**Comment by mcdmaster** [comment]
すみません、クローズ後に失礼します。

たとえば、エラー箇所の `push` 処理を `--force` 指定にした場合（`ad-m/github-push-action` のオプション `force: true` を指定する）、どんな問題があるでしょうか。
仮に Transifex で使用されているとしても、流れとしては、しかるべきタイミングで Transifex 側で解放されるべきモノのようにも見えます…
